[package]
name = "bored"
version = "0.1.0"
edition = "2024"

[dependencies.desi-ui]
path = "desi-ui"

[dependencies.uilang]
path = "uilang"

[dependencies.auto_with]
path = "auto_with"

[dependencies]
macroquad = "0.4.14"
